### PR TITLE
Switch to metrics-server 0.3.1

### PR DESCRIPTION
**Pull request by corest**

### CODE REVIEW

**Review by MarcelMue — APPROVED** [review]
LGTM I assume there are no breaking changes in a minor version upgrade.

**Review by rossf7 — APPROVED** [review]
LGTM but the version needs to be bumped in Chart.yaml.

This is a pain but we don't have a solution yet :( I think we could push `0.1.0-SHA` rather than `0.1.0` to Quay. We do that with draughtsman and the stable channel.

Bumping the major or minor version would still trigger a new release channel which we need for managed services.

**Comment by corest** [comment]
I didn't change chart version as the chart itself is not yet even the part of chart-operator, so that's like initial version will be `0.3.1`

**Comment by rossf7** [comment]
OK makes sense.

**Pull request merged**
